RecipeGeneratorWeb/AutoGener/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'AutoGener'
urlpatterns = [
    path(r'dish/delete/<name>', views.dish_delete, name='dish_delete'),
    path('dish/list_remove/<name>', views.dish_list_remove, name='dish_list_remove'),
    path('dish/addtype/', views.add_type, name="add_type"),
    path('dish/type_delete/<name>', views.type_delete, name='type_delete'),
    path('detail/<name>', views.get_dish_detail, name='dish_detail'),
    path(r'ingredient/<name>', views.ingre_delete, name='ingre_delete'),
    path('schedule/', views.get_scehdele, name='schedule'),
    path('dish/', views.get_dish, name='dish'),
    path('ingredient/', views.get_ingredient, name='ingredient')
]

RecipeGeneratorWeb/RecipeGeneratorWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from users import views

urlpatterns = [
    path('', include("AutoGener.urls")),
    path('', views.index, name="index"),
    path(r'users/', include('users.urls')),
    path(r'users/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

RecipeGeneratorWeb/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path(r'register/', views.register, name='register'),
]

RecipeGeneratorWeb/AutoGener/models.py
from django.db import models

# Create your models here.


class DishType(models.Model):
    """The type of the dish. A dish can have multiple types."""
    userid = models.IntegerField()
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class CanGet(models.Model):
    """ the ingredients user can get"""
    userid = models.IntegerField()
    name = models.CharField(max_length=10)
    cal = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return self.name


class CanDo(models.Model):
    """ the meal user can do"""
    userid = models.IntegerField()
    name = models.CharField(max_length=100)
    type = models.ManyToManyField(DishType)
    ingre = models.ManyToManyField(CanGet, blank=True)

    def __str__(self):
        return self.name


class Compose(models.Model):
    """the ingredient of a dish. A dish can have multiple ingredients."""
    dish = models.ForeignKey(CanDo, models.PROTECT)
    ingre = models.ForeignKey(CanGet, models.PROTECT)

    def __str__(self):
        return self.dish.name

RecipeGeneratorWeb/AutoGener/forms.py
from django import forms
from .models import CanGet, CanDo, DishType


class DishForm(forms.ModelForm):
    """form of ingredient that can be get"""
    name = forms.CharField(max_length=10)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(DishForm, self).__init__(*args, **kwargs)
        self.fields['type'] = forms.ModelMultipleChoiceField(
                widget=forms.CheckboxSelectMultiple, queryset=DishType.objects.filter(userid=self.user.id))

    class Meta:
        model = CanDo
        fields = ['name', 'type']
    #     labels = {
    #         'name': '菜名'
    #     }


class IngredientForm(forms.ModelForm):
    """form of ingredient that can be get"""
    name = forms.CharField(max_length=10)
    cal = forms.NumberInput()

    class Meta:
        model = CanGet
        fields = ['name', 'cal']

        labels = {
            'name': '食材'
        }

RecipeGeneratorWeb/AutoGener/views.py
from django.shortcuts import render, redirect, HttpResponse
from .forms import DishForm, IngredientForm
from .models import CanDo, CanGet, DishType
import random
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.contrib.auth.decorators import login_required
# Create your views here.

show_dishes = []


@login_required
def get_dish(request):
    """ /dish.html, deal with add new dish and redirect if there is a search. """
    form = DishForm(user=request.user)
    currentuser = request.user
    # 当前用户的cando list
    canDolist = CanDo.objects.filter(userid=currentuser.id)
    cangetlist = CanGet.objects.filter(userid=currentuser.id)
    message = ''
    types = DishType.objects.filter(userid=currentuser.id)
    if request.method == 'POST':
        detail = request.POST.get('dish_wanted')
        if detail:
            return get_dish_detail(request, detail, search=True)
        form = DishForm(request.POST, user=request.user)
        # check whether it's valid:
        if form.is_valid():
            # check notice
            new_dish_name = request.POST.get('name')
            dish_ingredient_str = request.POST.get('dish_ingredient')
            dish_ingredient_list = dish_ingredient_str.split('，')
            try:
                dish = canDolist.get(name=new_dish_name)
                # 菜已经存在, 但没有再次输入食材
                if not dish_ingredient_str:
                    message = '你已经有这道菜了,请重新输入'
                    context = {'canDolist': canDolist, 'form': form, 'message': message}
                    return render(request, 'AutoGener/dishform.html', context)
                # 菜已经存在，再次输入了食材，删除原食材重建
                else:
                    dish_delete(request, new_dish_name)
                    raise ObjectDoesNotExist

            # 菜不存在
            except ObjectDoesNotExist:
                # 新建菜
                dish = form.save(commit=False)
                dish.userid = currentuser.id
                dish.save()
                form.save_m2m()
                form = DishForm(user=request.user)
            if dish_ingredient_str:
                not_in_ingre = ''
                for ingredient in dish_ingredient_list:
                    try:
                        ingre = cangetlist.get(name=ingredient)
                        dish.ingre.add(ingre)
                    except ObjectDoesNotExist:
                        new_ingre = CanGet(userid=currentuser.id, name=ingredient)
                        new_ingre.save()
                        dish.ingre.add(new_ingre)
                        not_in_ingre += ingredient + '，'
                if not_in_ingre:
                    message = "以下食材不在食品库：%s 已经添加，但无法计算卡路里哦" % not_in_ingre
                else:
                    message = '添加成功！'
            # 菜存在，但是没有食材
            else:
                message = '成功添加，但没有记录食材'

    context = {'canDolist': canDolist, 'form': form, 'message': message, 'show_dishes': show_dishes,
               'types': types}
    return render(request, 'AutoGener/dishform.html', context)


@login_required
def dish_list_remove(request, name):
    """ remove dish=name from right side of /dish.html """
    try:
        dish = CanDo.objects.filter(userid=request.user.id).get(name=name)
        if dish in show_dishes:
            show_dishes.remove(dish)
        return redirect('/dish/')
    except ObjectDoesNotExist:
        return redirect('/dish/')


@login_required
def add_type(request):
    if request.method == 'GET':
        new_type = request.GET.get('new_type')
        if new_type:
            try:
                type = DishType.objects.filter(userid=request.user.id).get(name=new_type)
                # if already exist
                return HttpResponse('已存在')
            except ObjectDoesNotExist:
                type = DishType(userid=request.user.id, name=new_type)
                type.save()
    return redirect('/dish/')

# def type_filter(request, name):
#     type = get_object_or_404(DishType, name=name)
#     canDolist = type.cando_set.all()
#     form = DishForm()
#     message = ''
#     types = DishType.objects.all()
#     context = {'canDolist': canDolist, 'form': form, 'message': message, 'show_dishes': show_dishes,
#                'types': types}
#     return render(request, 'AutoGener/dishform.html', context)


@login_required
def get_dish_detail(request, name, search=False):
    """show dish detail on right side of /dish.html"""
    form = DishForm(user=request.user)
    message = ''
    canDolist = CanDo.objects.filter(userid=request.user.id)
    cangetlist = CanGet.objects.filter(userid=request.user.id)
    realted_dish = []
    ingre_list = []
    dish = CanDo()
    try:
        # 菜存在
        dish = canDolist.get(name=name)
        if dish not in show_dishes:
            show_dishes.append(dish)
        realted_dish = [dish]
        ingre_list = dish.ingre.all()
        for ingre in ingre_list:
            realted_dish += ingre.cando_set.filter(~Q(name=name)).all()
    except ObjectDoesNotExist:
        try:
            ingre = cangetlist.get(name=name)
            realted_dish = ingre.cando_set.all()
        except ObjectDoesNotExist:
            message = "%s不在你的菜单或食材库里" % name
    #不是搜索，显示所有菜
    if not search:
        context = {'canDolist': realted_dish, 'form': form, 'message': message, 'ingre_list': ingre_list, 'dish': dish,
                'show_dishes': show_dishes}
    #搜索，显示相关菜
    else:
        context = {'canDolist': realted_dish, 'form': form, 'message': message, 'ingre_list': ingre_list, 'dish': dish,
                   'show_dishes': show_dishes}
    return render(request, 'AutoGener/dishform.html', context)


@login_required
def get_ingredient(request):
    """ add new ingredient on /ingredient.html """
    form = IngredientForm(auto_id="ingre_%s")
    ingredientlist = CanGet.objects.filter(userid=request.user.id)
    duplicate = ''
    if request.method == 'POST':
        form = IngredientForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # check duplicate
            new_inge_name = request.POST.get('name')
            try:
                ingre = ingredientlist.get(name=new_inge_name)
                # 存在且卡路里数据相同
                if ingre.cal == int(request.POST.get('cal')):
                    duplicate = '已有该食材，请重新输入'
                else:
                    ingre.cal = int(request.POST.get('cal'))
                    ingre.save()
            except ObjectDoesNotExist:
                new_inge = form.save(commit=False)
                new_inge.userid = request.user.id
                new_inge.save()
                form = IngredientForm(auto_id="ingre_%s")
                duplicate = '添加/更新你的食材卡路里数据成功'
        else:
            duplicate = '请输入正确数据'

    context = {'ingredientlist': ingredientlist, 'form': form, 'duplicate': duplicate}
    return render(request, 'AutoGener/ingredientform.html', context)


@login_required
def ingre_delete(request, name):
    """delete ingre from database """
    ingredientlist = CanGet.objects.filter(userid=request.user.id)
    ingre = get_object_or_404(ingredientlist, name=name)
    ingre.delete()
    return redirect('/ingredient/')


@login_required
def dish_delete(request, name):
    """delete dish from database """
    canDolist = CanDo.objects.filter(userid=request.user.id)
    dish = get_object_or_404(canDolist, name=name)
    if dish in show_dishes:
        show_dishes.remove(dish)
    dish.delete()
    return redirect('/dish/')


@login_required
def type_delete(request, name):
    typelist = DishType.objects.filter(userid=request.user.id)
    type = get_object_or_404(typelist, name=name)
    type.delete()
    return redirect('/schedule/')


@login_required
def get_scehdele(request):
    """ randomly pick # of dishes from database """
    random_dish = []
    required_dish = []
    message = ''
    types = DishType.objects.filter(userid=request.user.id)
    canDolist = CanDo.objects.filter(userid=request.user.id)
    ingredientlist = CanGet.objects.filter(userid=request.user.id)
    if request.method == 'POST':
        need = request.POST.get('numNeed')
        want_eat = request.POST.get('wantEat')
        count = types.count()
        if not need.isdigit():
            message = '请输入数字'
        else:
            if count < int(need):
                message = '你的菜不足%s道哦' % need
                random_dish = CanDo.objects.all()
            if count == int(need):
                random_dish = CanDo.objects.all()
            else:
                random_dish = CanDo.objects.order_by('?')[:int(need)]
        # 如果有填写想吃的菜
        if want_eat:
            want_ingre = want_eat.split('，')
            # e.g. "鱼，虾"
            for ingre in want_ingre:
                # e.g. 所有名字里包含'虾'的食材
                ingre_list = ingredientlist.filter(Q(name__icontains=ingre))
                if ingre_list:
                    for ingredient in ingre_list:
                        required_dish += list(ingredient.cando_set.all())
                        if not required_dish:
                            message += '%s在你的食材库，但你没有菜用到了哦' % ingre + '； '
                # 如果ingre_list是空的，没有相关食材
                else:
                    message += '%s 不在你的食材库哦，请去添加' % ingre + '； '
    context = {'random_dish': random_dish, 'required_dish': list(set(required_dish)), "message": message,
               'types':types}
    return render(request, 'AutoGener/schedule.html', context)

RecipeGeneratorWeb/templates/AutoGener/dishform.html
{% extends 'base.html' %}
{% load i18n %}


{% block main %}
<div>
<form action="/dish/" method="post">
  <fieldset>
    <legend>{% trans "添加我会做的菜" %}</legend>
    {% csrf_token %}
    <div class="form-group">
      <label for="exampleInputPassword1">{% trans "菜名" %}</label>
      {{ form.name }}
    </div>

    <div class="form-group">
      <label for="exampleInputEmail1">{% trans "食材" %}</label>
      <form role="search" method="post" id="searchform" action="">
        <input type="text" name="dish_ingredient" placeholder="食材，用逗号隔开">
      </form>
    </div>

    <div class="form-group" id="type_list">
      <label for="exampleInputPassword1">{% trans "分类" %}</label>
      {{ form.type }}
      <form method="get" action="addtype/">
        <button type="submit" class="btn btn-link">+</button>
        <input type="text" name="new_type" style="width: 30%">
      </form>
    </div>

    <a class="btn btn-primary" target="_blank" href="{% url 'AutoGener:ingredient' %}" >{% trans "前往添加食材" %}</a>
    <button type="submit" class="btn btn-primary">{% trans "添加菜品" %}</button>
  </fieldset>
</form>
</div>
      <!--<div class="btn btn-link" id="aaaa">hhhh</div>-->

<br>
<br>
<div id="alertBlock">
  {% if message %}
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert" id="closeButton">&times;</button>
    <strong>{{ message }}</strong>
  </div>
  {% endif %}
</div>

<div >
  <h2>{% trans "我会做的菜" %}</h2>

  {% for dish in canDolist %}
    <p> <a href="{% url 'AutoGener:dish_detail' dish.name%}">{{ dish.name }}</a>
    <a class="close" href="{% url 'AutoGener:dish_delete' dish.name %}" >&times;</a>
    </p>
    <!--需要加上食材+克数=最终卡路里-->
  {% empty %}
    <div><p>{% trans "还没有会做的菜哦" %}</p></div>
  {% endfor %}
    </div>




{% endblock %}


{% block side %}
{% for dish in show_dishes %}
<div class="card border-primary mb-3" style="max-width: 20rem;">
  <div class="card-header">{{ dish.name }}
    <a class="close" href="{% url 'AutoGener:dish_list_remove' dish.name %}" >&times;</a>
  </div>

  <div class="card-body">
    <p class="card-text">
          {% for ingre in dish.ingre.all %}
      <div class="form-group">
          <label>{{ ingre.name }} </label>
            <form action="" method="post">
              {% csrf_token %}
              <input id="{{ dish.name }}{{ forloop.counter }}_weight"  min="0"  style="width: 18%"/>g&times;
              <input id="{{ dish.name }}{{ forloop.counter }}_data" value="{{ ingre.cal }}" style="width: 18%">cal/100g
              =<input class="{{ dish.name }}_cal_result" id="{{ dish.name }}{{ forloop.counter }}_each" style="width: 18%" disabled=""/>cal
            </form>
      </div>
   {% endfor %}
  <button id="{{ dish.name }}" onClick="reply_click(this.id)" class="btn btn-primary btn-sm">{% trans "计算" %}</button>
  total = <input id="{{ dish.name }}_cal" style="width: 18%" />cal

  </div>
</div>
{% endfor %}
{% endblock%}

RecipeGeneratorWeb/templates/AutoGener/ingredientform.html
{% extends 'base.html' %}
{% load i18n %}

{% block main %}
<div class = "dishBlock">
  <form action="/ingredient/" method="post">
    <fieldset>
      <legend>{% trans "添加食材" %}</legend>
      {% csrf_token %}
      <div class="form-group">
        <label for="exampleInputPassword1">{% trans "食材" %}:</label>
        {{ form.name }}
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">{% trans "卡路里" %}:</label>
        {{ form.cal }}cal/100g
        <small id="fileHelp" class="form-text text-muted">
          {% trans "查询" %}：<a href="http://www.boohee.com/food/" target="_blank">{% trans "卡路里查询" %}</a>
        </small>
        <small id="fileHelp" class="form-text text-muted">{% trans "单位不标准？：在右侧计算" %}</small>
        <small id="fileHelp" class="form-text text-muted">
          {% trans "摸不清准确卡路里数据？没关系，填大约值，在计算菜品总热量时可以即时修改" %}
        </small>
      </div>

      <a class="btn btn-primary" target="_blank" href="{% url 'AutoGener:dish' %}" >{% trans "前往添加新菜" %}</a>
      <button type="submit" class="btn btn-primary">{% trans "添加食材" %}</button>
    </fieldset>
  </form>
</div>


<br>
<div id="alertBlock">
  {% if duplicate %}
  <div class="alert alert-dismissible alert-danger">
    <button type="button" class="close" data-dismiss="alert" id="closeButton">&times;</button>
    <strong>{{ duplicate }}</strong>
  </div>
  {% endif %}
</div>

<br>
<br>

<div>
  <div>
  <h2>{% trans "我能买到的食材" %}</h2>
  <br>
  {% for ingre in ingredientlist %}
        <p> <a href="{% url 'AutoGener:dish_detail' ingre.name %}">{{ ingre.name }}</a> {{ ingre.cal }}cal/100g
          <a class="close" href="{% url 'AutoGener:ingre_delete' ingre.name %}" >&times;</a>
        </p>
  {% empty %}
    <div><p>{% trans "还没有食材哦" %}！</p></div>
  {% endfor %}
    </div>
</div>


{% endblock %}





{% block side %}
  <div>
  <legend>{% trans "简单计算" %}</legend>
    <p>{% trans "单位不规则？在下方输入数据" %}
    <br>
    <input id="calo" class="col-form-label col-form-label-sm" placeholder="cal" />cal
    <br>
    <br>
    <input id="weight" class="col-form-label col-form-label-sm" placeholder="{% trans '输入食材或菜品' %}" />g
    <br>
    <br>
    <button class="btn btn-primary" id="calculate" >{% trans "计算并填到左边" %}</button>

  </div>
{% endblock %}

RecipeGeneratorWeb/templates/AutoGener/schedule.html
{% extends 'base.html' %}
{% load i18n %}

{% block left %}

{% for dish in random_dish %}
<div class="card border-primary mb-3" style="max-width: 20rem;">
  <div class="card-header">{{ dish.name }}
  </div>
  <div class="card-body">
    <p class="card-text">
          {% for ingre in dish.ingre.all %}
      <div class="form-group">
          <label>{{ ingre.name }} </label>
            <form action="" method="post">
              {% csrf_token %}
              <input id="{{ dish.name }}{{ forloop.counter }}_weight"  min="0" placeholder="克数" style="width: 18%"/>g&times;
              <input id="{{ dish.name }}{{ forloop.counter }}_data" value="{{ ingre.cal }}" style="width: 18%">cal/100g
              =<input class="{{ dish.name }}_cal_result" id="{{ dish.name }}{{ forloop.counter }}_each" style="width: 18%" disabled=""/>cal
            </form>
      </div>
   {% endfor %}
  <button id="{{ dish.name }}" onClick="reply_click(this.id)" class="btn btn-primary btn-sm">{% trans "计算" %}</button>
  total = <input id="{{ dish.name }}_cal" style="width: 18%" />cal

  </div>
</div>
{% endfor %}

{% endblock%}




<!--<div class = "dishBlock">-->
<!--<div class="btn-group-vertical" data-toggle="buttons">-->
    <!--<form action="/schedule/" method="post">-->
            <!--{% csrf_token %}-->
        <!--<div class="form-group">-->
          <!--<legend>需要几道不同的菜？</legend>-->
          <!--<input type="text" class="form-control" name="numNeed" placeholder="需要道数">-->
          <!--<legend>指定想吃食材</legend>-->
          <!--<input type="text" class="form-control" name="wantEat" placeholder="已有/想吃食材，用逗号隔开">-->
        <!--</div>-->
        <!--<button type="submit" class="btn btn-primary">随机抽取</button>-->
    <!--</form>-->
<!--</div>-->
<!--</div>-->

<!--<br>-->

<!--<div id="alertBlock">-->
  <!--{% if message %}-->
  <!--<div class="alert alert-dismissible alert-danger">-->
    <!--<button type="button" class="close" data-dismiss="alert" id="closeButton">&times;</button>-->
    <!--<strong>{{ message }}</strong>-->
  <!--</div>-->
  <!--{% endif %}-->
<!--</div>-->

<!--<br>-->



<!--<div class = "dishBlock">-->
  <!--<div>-->
  <!--<h2>安排下列菜品咯</h2>-->
  <!--<br>-->
  <!--{% for dish in random_dish %}-->
      <!--<p> <a href="{% url 'AutoGener:dish_detail' dish.name %}">{{ dish.name }}</a></p>-->
  <!--{% empty %}-->
      <!--<div><p>还没有添加会做的菜哦哦！<a hred="{% url 'AutoGener:dish'%}">点击添加</a></p></div>-->
  <!--</div>-->
  <!--{% endfor %}-->
  <!--{% if required_dish %}-->
  <!--<p>包含输入的食材的菜:</p>-->
  <!--{% for dish in required_dish %}-->
      <!--<p> <a href="{% url 'AutoGener:dish_detail' dish.name %}">{{ dish.name }}</a></p>-->
  <!--{% endfor %}-->
  <!--{% endif %}-->
<!--</div>-->

<!--<div class = "dishBlock">-->
<!--<div class="btn-group-vertical" data-toggle="buttons">-->
    <!--<form action="/schedule/" method="post">-->
            <!--{% csrf_token %}-->
         <!--<button type="submit" class="btn btn-primary">安排上吧</button>-->
    <!--</form>-->
<!--</div>-->
<!--</div>-->




{% block main %}

{% for type in types %}
<br>


<div class="card border-primary mb-3" style="max-width: 20rem;">
  <div class="card-header">{{ type.name }}:<a class="close" href="{% url 'AutoGener:type_delete' type.name %}">x</a></div>
  <div class="card-body">
    {% for dish in type.cando_set.all %}
      <div id="{{ type.name}}_{{ forloop.counter }}" draggable="true" ondragstart="drag(event)">
        <p class="card-text">{{ dish.name }}</p>
      </div>
    {% empty %}
      {% trans "没有菜品" %}
      <br>
    {% endfor %}
  </div>
</div>

{% endfor %}

{% endblock %}


{% block side %}
<div class = "tables" style="position: fixed;">
  <table>
    <tr>
      <th class="tg-88nc" ondrop="dropdelete(event)" ondragover="allowDrop(event)">🗑️</th>
      <th class="tg-88nc">Mon</th>
      <th class="tg-88nc">Tue</th>
      <th class="tg-9hbo">Wed</th>
      <th class="tg-9hbo">Thu</th>
      <th class="tg-9hbo">Fri</th>
      <th class="tg-9hbo">Sal</th>
      <th class="tg-9hbo">Sun</th>
    </tr>
    <tr>
      <td class="tg-88nc">AM</td>
      <td id="table-a1" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-a2" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-a3" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-a4" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-a5" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-a6" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-a7" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
    </tr>
    <tr>
      <td class="tg-88nc">NOON</td>
      <td id="table-n1" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-n2" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-n3" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-n4" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-n5" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-n6" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-n7" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
    </tr>
    <tr>
      <td class="tg-88nc">PM</td>
      <td id="table-p1" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-p2" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-p3" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-p4" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-p5" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-p6" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
      <td id="table-p7" ondrop="drop(event)" ondragover="allowDrop(event)"></td>
    </tr>
  </table>
  <div class="form-group">
      <h3>Note:</h3><small class="text-muted">记录要买的食材</small>

      <textarea class="form-control" id="exampleTextarea" rows="3" style="margin-top: 0px; margin-bottom: 0px; height: 177px;"></textarea>
    </div>
</div>

{% endblock %}