RecipeGeneratorWeb/AutoGener/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'AutoGener'
urlpatterns = [
    path(r'dish/delete/<name>', views.dish_delete, name='dish_delete'),
    path('dish/list_remove/<name>', views.dish_list_remove, name='dish_list_remove'),
    path('dish/addtype/', views.add_type, name="add_type"),
    path('dish/type_delete/<name>', views.type_delete, name='type_delete'),
    path('detail/<name>', views.get_dish_detail, name='dish_detail'),
    path(r'ingredient/<name>', views.ingre_delete, name='ingre_delete'),
    path('schedule/', views.get_scehdele, name='schedule'),
    path('dish/', views.get_dish, name='dish'),
    path('ingredient/', views.get_ingredient, name='ingredient')
]

RecipeGeneratorWeb/RecipeGeneratorWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from users import views

urlpatterns = [
    path('', include("AutoGener.urls")),
    path('', views.index, name="index"),
    path(r'users/', include('users.urls')),
    path(r'users/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

RecipeGeneratorWeb/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path(r'register/', views.register, name='register'),
]

RecipeGeneratorWeb/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% trans "排排菜，安排你的一周食谱" %}</title>
    <link rel="stylesheet" href="{% static 'AutoGener/css/bootstrap.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

</head>
<body style="background-color:hsl(0, 0%, 99%)">

<style>
table, td, th {
    border: 1px solid #ddd;
    text-align: left;
}

table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    padding: 15px;
}

  ul
{
    list-style-type: none;
}

  <!--.tg{-->
    <!--border-collapse:collapse;-->
    <!--border-spacing:0;-->
  <!--}-->
  <!--.tg td{-->
    <!--font-family:Arial, sans-serif;-->
    <!--font-size:14px;-->
    <!--padding:10px 5px;-->
    <!--border-style:solid;-->
    <!--border-width:1px;-->
    <!--overflow:hidden;-->
    <!--word-break:normal;-->
    <!--border-color:black;-->
  <!--}-->
  <!--.tg th{-->
    <!--font-family:Arial, sans-serif;-->
    <!--font-size:14px;-->
    <!--font-weight:normal;-->
    <!--padding:10px 5px;-->
    <!--border-style:solid;-->
    <!--border-width:1px;-->
    <!--overflow:hidden;-->
    <!--word-break:normal;-->
    <!--border-color:black;-->
  <!--}-->
  <!--.tg .tg-88nc{-->
    <!--font-weight:bold;-->
    <!--border-color:inherit;-->
    <!--text-align:center-->
  <!--}-->
  <!--.tg .tg-uys7{-->
    <!--border-color:inherit;-->
    <!--text-align:center;-->
  <!--}-->
  <!--.tg .tg-9hbo{-->
    <!--font-weight:bold;-->
    <!--vertical-align:top;-->
  <!--}-->
  <!--.tg .tg-yw4l{-->
    <!--vertical-align:top;-->
  <!--}-->

  <!--.foodbasket{-->
    <!--padding:3%;-->
    <!--background-color: #a4a4a4;-->
    <!--border:3px solid #000;-->
    <!--border-radius: 2em;-->
    <!--width:100%;-->
    <!--min-height:200px;-->
  <!--}-->

  <!--.edit-block{-->
    <!--display:block;-->
  <!--}-->

  <!--.tables{-->
    <!--margin:30px 0;-->
  <!--}-->

  </style>

<script type="text/javascript">
  $(function (){
  $("#calculate").click(function(){
    var cal = parseInt(parseInt($("#calo").val()*100/$("#weight").val()));
    $("#ingre_cal").val(cal);
  })
  })
</script>


<script type="text/javascript">
function reply_click(name)
{
          var x = document.getElementsByClassName(name + "_cal_result").length;
		  var i;
		  var total = 0;
		  for (i = 1; i < x + 1; i++) {
            var product = (parseInt(document.getElementById(name+i+"_weight").value)*parseInt(document.getElementById(name+i+"_data").value))/100;
            document.getElementById(name+i+"_each").value = product;
            total += parseInt(product) || 0;
          }
          document.getElementById(name+'_cal').value = total;
}
</script>

<script>
function allowDrop(ev) {
    ev.preventDefault();
}

function drag(ev) {
    ev.dataTransfer.setData("text", ev.target.id);
}

function drop(ev) {
    ev.preventDefault();
    var data = ev.dataTransfer.getData("text");
    var nodeCopy = document.getElementById(data).cloneNode(true);
    nodeCopy.id = data + ev.id
    <!--alert(data + ev.target.id)-->
    ev.target.appendChild(nodeCopy);
}
function dropdelete(ev) {
    ev.preventDefault();
    var data = ev.dataTransfer.getData("text");
    var el = document.getElementById(data)
    el.parentNode.removeChild(el);
}
</script>

<script>
  $(document).ready(function(){
    $("#closeButton").click(function(){
      $("#alertBlock").remove();
    });
  });
</script>

<script>
  $(document).ready(function(){
    $("#aaaa").click(function(){
    var type_name=document.getElementById('type_name').value;
      $.ajax({
      url:"{% url 'AutoGener:add_type' %}",
      data:{name:type_name},
      success:function(result){
        alert(result);
        };
    });
  });
</script>


<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{% url 'index' %}">{% trans "排排菜" %}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">{% trans "首页" %}<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'AutoGener:schedule' %}">{% trans "一周安排" %}</a>
      </li>
            <li class="nav-item active">
        <a class="nav-link" href="{% url 'AutoGener:dish' %}">{% trans "我的菜单" %}</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'AutoGener:ingredient' %}">{% trans "我的食材" %}</a>
      </li>
      <li class="nav-item active">
    <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'AutoGener:dish' %}">
        {% csrf_token %}
      <input class="form-control mr-sm-2" type="text" placeholder="{% trans '输入食材或菜品' %}" name="dish_wanted">
      {% if dish.name %}
        <a href="{% url 'AutoGener:dish' %}" class="btn btn-secondary my-2 my-sm-0">{% trans "返回" %}</a>
      {% else %}
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">{% trans "搜索" %}</button>
      {% endif %}
    </form>
      </li>

    </ul>

        <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
          <input type="hidden" value="{{ redirect_to }}">
          <select name="language" class="form-control " onChange="form.submit();">
              {% get_current_language as LANGUAGE_CODE %}
              {% get_available_languages as LANGUAGES %}
              {% get_language_info_list for LANGUAGES as languages %}
              {% for language in languages %}
                  <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                      {{ language.name_local }}
                  </option>
              {% endfor %}
          </select>
         </form>
  </div>
</nav>




<br>
<br>
<div class = "row">

  <div class="col-md-2">
    {% block left %}
    {% endblock %}
  </div>
<div class="col-md-4">
  {% block main %}

  {% endblock %}
</div>

<div class="col-lg-6">
    {% block side %}

    {% endblock %}
</div>


</div>
</body>
</html>

RecipeGeneratorWeb/templates/home.html
{% extends 'base.html' %}
{% load i18n %}
<!--背景不显示呜呜呜-->
{% block main %}
<div class="flex-center">
    <div class="container">
        <div>
            {% if user.is_authenticated %}
                 <h1>{{ user.username }} {% trans '已登录，欢迎你' %} </h1>
                 <button class="btn btn-default"><a href="{% url 'logout' %}?next={{ request.path }}">{% trans '注销登录' %}</a></button>
                  <button class="btn btn-default"><a href="{% url 'password_change' %}?next={{ request.path }}">{% trans '修改密码' %}</a>
            {% else %}
                <p>{% trans '你还没有登录，请' %}
                    <button class="btn btn-default"><a href="{% url 'login' %}?next={{ request.path }}">{% trans '登录' %}</a></button>

                    <button class="btn btn-default"><a href="{% url 'users:register' %}">{% trans '注册' %}</a></button>

  </button>
                </p>

            {% endif %}
        </div>
    </div>
</div>


<div  class="jumbotron">
  <img>
  <h1 class="display-3">{% trans '一周饮食' %}<br>{% trans '尽在掌握' %}</h1>
  <p class="lead">{% trans '你好，更有规划的生活方式。' %}</p>
  <hr class="my-4">
  <p>{% trans '根据生成的购物清单，一次购置一周食材。清晰又节省。' %}</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="{% url 'AutoGener:dish' %}">{% trans '从添加我会做的菜开始' %}</a>
  </p>
</div>

{% endblock %}